<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.fei.base</groupId>
        <artifactId>base-parent</artifactId>
        <version>1.2.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>microservice-base-generator</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>modules/common/dal</module>
        <module>modules/common/util</module>
        <module>modules/common/service/integration</module>
        <module>modules/core/model</module>
        <module>modules/core/service</module>
        <module>modules/rpc/facade</module>
        <module>modules/biz/shared</module>
        <module>modules/biz/service</module>
        <module>modules/biz/facade/impl</module>
        <module>modules/test</module>
        <module>modules/web/api</module>
        <module>assembly/template</module>
        <module>deploy</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- demo project depends -->
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-common-dal</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-common-util</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-common-service-integration</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-core-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-core-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-rpc-facade</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-biz-shared</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-biz-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-biz-facade-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-assembly-template</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-deploy</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-test</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fei.base</groupId>
                <artifactId>microservice-base-generator-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc-openapi-starter-webmvc-ui.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <defaultGoal>install</defaultGoal>
        <plugins>
            <plugin>
                <groupId>cn.dalgen.plugins</groupId>
                <artifactId>mybatis-maven-plugin</artifactId>
                <version>1.1.1</version>
                <configuration>
                    <templateDirectory>dalgen/templates</templateDirectory>
                    <outputDirectory>${project.artifactId}/common/dal/src</outputDirectory>
                    <config>dalgen/config/config.xml</config>
                    <copyTemplate>false</copyTemplate>
                </configuration>
                <inherited>false</inherited>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <distributionManagement>
        <snapshotRepository>
            <id>nexus-snapshots</id>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
        </snapshotRepository>
        <repository>
            <id>nexus-releases</id>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
        </repository>
    </distributionManagement>
</project>
