spring:
  profiles:
    active: dev
  application:
    name: microservice-base-generator
app:
  id: ${spring.application.name}
apollo:
  bootstrap:
    enabled: true
    namespaces: application,common.yaml,db